# use g++ compiler
CXX=g++
CXXFLAGS?=-Wall -pedantic -std=c++11

# output format (use -DOUTCOMPACT for the compact output format)
OUTFLAG=-DOUTFAVITES

# flag specifications for release and debug
RELEASEFLAGS?=$(CXXFLAGS) $(OUTFLAG) -O3
DEBUGFLAGS?=$(CXXFLAGS) $(OUTFLAG) -O0 -g #-pg

# relevant constants
CPP_FILES=main.cpp common.cpp writer.cpp
HEADER_FILES=common.h
GLOBAL_DEPS=$(CPP_FILES) $(HEADER_FILES)
EXE_PREFIX=ngg
DEBUG_SUFFIX=debug

# Barabasi-Albert graph
BA=barabasi_albert
BA_EXE=$(EXE_PREFIX)_$(BA)
BA_DEBUG=$(BA)_$(DEBUG_SUFFIX)
BA_DEBUG_EXE=$(EXE_PREFIX)_$(BA_DEBUG)
BA_CPP=barabasi_albert.cpp
BA_H=barabasi_albert.h
BA_FILES=$(BA_CPP) $(BA_H)

# barbell graph
BARBELL=barbell
BARBELL_EXE=$(EXE_PREFIX)_$(BARBELL)
BARBELL_DEBUG=$(BARBELL)_$(DEBUG_SUFFIX)
BARBELL_DEBUG_EXE=$(EXE_PREFIX)_$(BARBELL_DEBUG)
BARBELL_CPP=barbell.cpp
BARBELL_H=barbell.h
BARBELL_FILES=$(BARBELL_CPP) $(BARBELL_H)

# complete graph
COMPLETE=complete
COMPLETE_EXE=$(EXE_PREFIX)_$(COMPLETE)
COMPLETE_DEBUG=$(COMPLETE)_$(DEBUG_SUFFIX)
COMPLETE_DEBUG_EXE=$(EXE_PREFIX)_$(COMPLETE_DEBUG)
COMPLETE_CPP=complete.cpp
COMPLETE_H=complete.h
COMPLETE_FILES=$(COMPLETE_CPP) $(COMPLETE_H)

# cycle graph
CYCLE=cycle
CYCLE_EXE=$(EXE_PREFIX)_$(CYCLE)
CYCLE_DEBUG=$(CYCLE)_$(DEBUG_SUFFIX)
CYCLE_DEBUG_EXE=$(EXE_PREFIX)_$(CYCLE_DEBUG)
CYCLE_CPP=cycle.cpp path.cpp
CYCLE_H=cycle.h
CYCLE_FILES=$(CYCLE_CPP) $(CYCLE_H)

# empty graph
EMPTY=empty
EMPTY_EXE=$(EXE_PREFIX)_$(EMPTY)
EMPTY_DEBUG=$(EMPTY)_$(DEBUG_SUFFIX)
EMPTY_DEBUG_EXE=$(EXE_PREFIX)_$(EMPTY_DEBUG)

# Erdos-Renyi graph
ER=erdos_renyi
ER_EXE=$(EXE_PREFIX)_$(ER)
ER_DEBUG=$(ER)_$(DEBUG_SUFFIX)
ER_DEBUG_EXE=$(EXE_PREFIX)_$(ER_DEBUG)
ER_CPP=erdos_renyi.cpp
ER_H=erdos_renyi.h
ER_FILES=$(ER_CPP) $(ER_H)

# path graph
PATHGRAPH=path
PATHGRAPH_EXE=$(EXE_PREFIX)_$(PATHGRAPH)
PATHGRAPH_DEBUG=$(PATHGRAPH)_$(DEBUG_SUFFIX)
PATHGRAPH_DEBUG_EXE=$(EXE_PREFIX)_$(PATHGRAPH_DEBUG)
PATHGRAPH_CPP=path.cpp
PATHGRAPH_H=path.h
PATHGRAPH_FILES=$(PATHGRAPH_CPP) $(PATHGRAPH_H)

# compile all executables
RELEASE_EXES=$(BA_EXE) $(BARBELL_EXE) $(COMPLETE_EXE) $(CYCLE_EXE) $(EMPTY_EXE) $(ER_EXE) $(PATHGRAPH_EXE)
DEBUG_EXES=$(BA_DEBUG_EXE) $(BARBELL_DEBUG_EXE) $(COMPLETE_DEBUG_EXE) $(CYCLE_DEBUG_EXE) $(EMPTY_DEBUG_EXE) $(ER_DEBUG_EXE) $(PATHGRAPH_DEBUG_EXE)
all: $(RELEASE_EXES)
debug: $(DEBUG_EXES)

# Barabasi-Albert graph
BA_FLAG=-DBA
$(BA_EXE): $(GLOBAL_DEPS) $(BA_FILES)
	$(CXX) $(RELEASEFLAGS) $(BA_FLAG) -o $(BA_EXE) $(CPP_FILES) $(BA_CPP)
$(BA_DEBUG_EXE): $(GLOBAL_DEPS) $(BA_FILES)
	$(CXX) $(DEBUGFLAGS) $(BA_FLAG) -o $(BA_DEBUG_EXE) $(CPP_FILES) $(BA_CPP)

# barbell graph
BARBELL_FLAG=-DBARBELL
$(BARBELL_EXE): $(GLOBAL_DEPS) $(BARBELL_FILES)
	$(CXX) $(RELEASEFLAGS) $(BARBELL_FLAG) -o $(BARBELL_EXE) $(CPP_FILES) $(BARBELL_CPP)
$(BARBELL_DEBUG_EXE): $(GLOBAL_DEPS) $(BARBELL_FILES)
	$(CXX) $(DEBUGFLAGS) $(BARBELL_FLAG) -o $(BARBELL_DEBUG_EXE) $(CPP_FILES) $(BARBELL_CPP)

# complete graph
COMPLETE_FLAG=-DCOMPLETE
$(COMPLETE_EXE): $(GLOBAL_DEPS) $(COMPLETE_FILES)
	$(CXX) $(RELEASEFLAGS) $(COMPLETE_FLAG) -o $(COMPLETE_EXE) $(CPP_FILES) $(COMPLETE_CPP)
$(COMPLETE_DEBUG_EXE): $(GLOBAL_DEPS) $(COMPLETE_FILES)
	$(CXX) $(DEBUGFLAGS) $(COMPLETE_FLAG) -o $(COMPLETE_DEBUG_EXE) $(CPP_FILES) $(COMPLETE_CPP)

# cycle graph
CYCLE_FLAG=-DCYCLE
$(CYCLE_EXE): $(GLOBAL_DEPS) $(CYCLE_FILES)
	$(CXX) $(RELEASEFLAGS) $(CYCLE_FLAG) -o $(CYCLE_EXE) $(CPP_FILES) $(CYCLE_CPP)
$(CYCLE_DEBUG_EXE): $(GLOBAL_DEPS) $(CYCLE_FILES)
	$(CXX) $(DEBUGFLAGS) $(CYCLE_FLAG) -o $(CYCLE_DEBUG_EXE) $(CPP_FILES) $(CYCLE_CPP)

# empty graph
EMPTY_FLAG=-DEMPTY
$(EMPTY_EXE): $(GLOBAL_DEPS)
	$(CXX) $(RELEASEFLAGS) $(EMPTY_FLAG) -o $(EMPTY_EXE) $(CPP_FILES)
$(EMPTY_DEBUG_EXE): $(GLOBAL_DEPS)
	$(CXX) $(DEBUGFLAGS) $(EMPTY_FLAG) -o $(EMPTY_DEBUG_EXE) $(CPP_FILES)

# Erdos-Renyi graph
ER_FLAG=-DER
$(ER_EXE): $(GLOBAL_DEPS) $(ER_FILES)
	$(CXX) $(RELEASEFLAGS) $(ER_FLAG) -o $(ER_EXE) $(CPP_FILES) $(ER_CPP)
$(ER_DEBUG_EXE): $(GLOBAL_DEPS) $(ER_FILES)
	$(CXX) $(DEBUGFLAGS) $(ER_FLAG) -o $(ER_DEBUG_EXE) $(CPP_FILES) $(ER_CPP)

# path graph
PATHGRAPH_FLAG=-DPATHGRAPH
$(PATHGRAPH_EXE): $(GLOBAL_DEPS) $(PATHGRAPH_FILES)
	$(CXX) $(RELEASEFLAGS) $(PATHGRAPH_FLAG) -o $(PATHGRAPH_EXE) $(CPP_FILES) $(PATHGRAPH_CPP)
$(PATHGRAPH_DEBUG_EXE): $(GLOBAL_DEPS) $(PATHGRAPH_FILES)
	$(CXX) $(DEBUGFLAGS) $(PATHGRAPH_FLAG) -o $(PATHGRAPH_DEBUG_EXE) $(CPP_FILES) $(PATHGRAPH_CPP)

# clean things up
clean:
	$(RM) $(RELEASE_EXES) $(DEBUG_EXES) *.o
